# Generated by Django 2.1.2 on 2019-02-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_company', models.CharField(max_length=100)),
                ('job_link', models.CharField(max_length=300)),
                ('job_applied', models.BooleanField(default=False)),
                ('job_qualified', models.IntegerField(default=0)),
                ('job_application_status', models.IntegerField(default=0)),
                ('job_last_action', models.DateField()),
                ('job_comment', models.TextField(default="Job Pulled, let's apply")),
            ],
        ),
    ]
